# Generated by Django 5.2.5 on 2025-12-01 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('ordersapp', '0002_order_delivered_at_order_status_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event name or identifier', max_length=255)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('corporate', 'Corporate'), ('party', 'Private Party'), ('other', 'Other')], default='other', max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('location', models.TextField()),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('dietary_notes', models.TextField(blank=True)),
                ('billing_contact_name', models.CharField(blank=True, max_length=255)),
                ('billing_contact_phone', models.CharField(blank=True, max_length=50)),
                ('billing_contact_email', models.EmailField(blank=True, max_length=254)),
                ('additional_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['-event_date', '-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='ordersapp.event'),
        ),
    ]
