# Generated by Django 5.2.5 on 2025-12-01 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0004_menucategory_menupackage_menuitem_menupackageitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Portions or kg as entered')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ordersapp.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='ordersapp.order')),
            ],
        ),
    ]
