# Generated by Django 5.2.5 on 2025-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0005_ordermenuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ordermenuitem',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
