# Generated by Django 4.2.23 on 2025-09-26 12:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Units of Measure',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('RAW', 'Raw'), ('CONS', 'Consumable'), ('ASSET', 'Asset'), ('SVC', 'Service')], default='RAW', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_uom', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_available', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_reserved', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_in_use', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_damaged', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
