# Generated by Django 5.2.5 on 2025-10-09 17:29

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_supplier'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Inventory Categories',
            },
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier',
        ),
        migrations.CreateModel(
            name='InventoryBaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('RAW', 'Raw'), ('CONS', 'Consumable'), ('ASSET', 'Asset'), ('SVC', 'Service')], default='RAW', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_uom', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=12)),
                ('qty_on_hand', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_available', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_reserved', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_in_use', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('qty_damaged', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='suppliers.supplier')),
                ('uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.unitofmeasure')),
            ],
            options={
                'verbose_name_plural': 'Inventory Base Items',
            },
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.inventorycategory'),
        ),
    ]
