# Generated by Django 5.2.5 on 2025-12-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorycategory_remove_inventoryitem_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='min_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Warn when quantity is at or below this level'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'In'), ('OUT', 'Out'), ('ADJ', 'Adjust')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.inventoryitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
